# Generated by Django 4.2.10 on 2024-02-18 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(default='', max_length=50, unique=True)),
                ('investor_type', models.CharField(choices=[('BUSINESS_ANGELS', 'Business Angels'), ('VC', 'VCs'), ('FAMILY_OFFICE', 'Family Office'), ('FOUNDATION', 'Foundation'), ('ALL_INVESTOR', 'All of them')], default='ALL_INVESTOR', max_length=20)),
                ('investor_expertise', models.CharField(choices=[('ACCOUNTING', 'Accounting'), ('CONTROLLING', 'Controlling'), ('FUNDRAISING', 'Fundraising'), ('HR', 'HR'), ('LEGAL', 'Legal'), ('LOGISTICS', 'Logistics'), ('MANAGEMENT', 'Management'), ('MARKTING', 'Marketing'), ('PR', 'PR'), ('PROCUREMENT', 'Procurement'), ('PRODUCT_DEVELOPEMENT', 'Product Development'), ('PRODUCTION', 'Production'), ('SALES', 'Sales'), ('STRATEGY', 'Strategy'), ('TECHNOLOGY', 'Technology'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('investor_value', models.CharField(choices=[('HAS_CONTACT', 'he brings a lot of contacts with him'), ('KNOWS_INDUSTRY', 'he knows your industry very well'), ('HAS_VISION', 'he he represents my vision'), ('COVER_VALUES', 'covers my values'), ('KNOWS_TECH', 'has technical know-how'), ('HAS_IMPACT', 'we share the same impact thought'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('capital_required', models.IntegerField(default=100000)),
                ('location', models.CharField(choices=[('SOUTH_AFRICA', 'South Africa'), ('RWANDA', 'Rwanda')], default='SOUTH_AFRICA', max_length=20)),
                ('stage', models.CharField(choices=[('PRE_SEED', 'Pre-Seed'), ('SEED', 'Seed'), ('SERIES_A', 'Series A'), ('SERIES_B', 'Series B'), ('SERIES_C', 'Series C')], default='PRE_SEED', max_length=10)),
                ('industry', models.CharField(choices=[('REAL_ESTATE', 'Real Estate'), ('NATURE_PROTECTION', 'Nature Protection'), ('WOMAN_EMPOWERMENT', 'Woman Empowerment'), ('POVERTY_ALLEVIATION', 'Poverty Alleviation'), ('GREENTECH', 'Greentech'), ('SMART_CITY', 'Smart City'), ('MOBILITY', 'Mobility'), ('ENERGY', 'Energy'), ('EDUCATION', 'Education'), ('HEALTH', 'Health'), ('SPORTS', 'Sports'), ('COSMETICS', 'Cosmetics'), ('FINANCIAL_AND_INSURANCE', 'Financial & Insurance'), ('FOOD', 'Food'), ('LEGAL_SERVICES', 'Legal'), ('RENTAL_AND_REPAIR', 'Rental & Repair'), ('TRANSPORTATION_AND_STORAGE', 'Transportation & Storage'), ('INFORMATION_AND_COMMUNICATION', 'Information & Communication'), ('ENTERTAINMENT_AND_RECREATION', 'Arts, Entertainment & Recreation'), ('SUPPORT_SERVICES', 'Support Services'), ('TECHNICAL_SERVICES', 'Technical Services'), ('ENVIRONMENTAL_CONSULTING', 'Environmental Consulting'), ('OTHER', 'Other'), ('NONE', 'None')], default='NONE', max_length=30)),
                ('business_type', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('CONSULTANCY', 'Consultancy'), ('FOR_PROFIT', 'For Profit'), ('NON_PROFIT', 'Non Profit')], default='B2B', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
